#!/usr/bin/env python3
"""
Minifies and GZIP-compresses web_ui.html → index_html_gz.h
Usage: compress_ui.py <input.html> <output.h>
"""
import sys
import os
import gzip
import re


def inline_assets(content: str, base_dir: str) -> str:
    """Ersetzt <!--INLINE:relpath--> durch den Dateiinhalt aus base_dir/relpath.

    Hintergrund: Externe CDN-Skripte werden von "Tracking Prevention"
    (Edge/Brave/Safari) regelmäßig blockiert. Library-Code (z.B. qrcode.min.js)
    deshalb lokal halten und beim Build ins HTML einbetten.

    Wir entfernen außerdem `//# sourceMappingURL=...` Kommentare, damit der
    Browser nicht versucht, eine externe Source-Map zu laden, die im
    inlined Kontext sowieso nicht funktioniert.
    """
    pattern = re.compile(r'<!--\s*INLINE:(\S+?)\s*-->')

    def _replace(match):
        rel = match.group(1)
        path = os.path.join(base_dir, rel)
        if not os.path.exists(path):
            print(f'[WebUI] WARNUNG: INLINE-Asset nicht gefunden: {rel}')
            return ''
        with open(path, 'r', encoding='utf-8') as f:
            data = f.read()
        # SourceMap-Verweise entfernen (zeigt sonst auf nicht existierende URL)
        data = re.sub(r'^\s*//[#@]\s*sourceMappingURL=.*$', '', data, flags=re.MULTILINE)
        return data

    return pattern.sub(_replace, content)


def minify_html(content: str) -> str:
    # 1. Inline-Assets sind bereits eingebettet — wir splitten <script>-Bereiche
    #    aus, damit die HTML-Whitespace-Regeln den JS-Code nicht beschädigen.
    parts = re.split(r'(<script\b[^>]*>.*?</script>)', content, flags=re.DOTALL | re.IGNORECASE)

    out = []
    for part in parts:
        if part.lower().startswith('<script'):
            # JS-Block: nur leere Zeilen entfernen, sonst unverändert lassen
            out.append(part)
            continue
        # HTML/CSS-Block: aggressiv minifizieren
        # Remove HTML comments (keep IE conditionals)
        p = re.sub(r'<!--(?!\[if).*?-->', '', part, flags=re.DOTALL)
        # Collapse whitespace between tags
        p = re.sub(r'>\s+<', '><', p)
        # Collapse runs of whitespace
        p = re.sub(r' {2,}', ' ', p)
        lines = [line.strip() for line in p.split('\n')]
        out.append(''.join(line for line in lines if line))
    return ''.join(out)


def main():
    if len(sys.argv) != 3:
        print('Usage: compress_ui.py <input.html> <output.h>')
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = sys.argv[2]

    # Smart incremental build: skip if output is newer than input AND
    # any inline-Asset (z.B. qrcode.min.js).
    def _newest_input_mtime():
        newest = os.path.getmtime(in_path)
        try:
            with open(in_path, 'r', encoding='utf-8') as f:
                src = f.read()
            for rel in re.findall(r'<!--\s*INLINE:(\S+?)\s*-->', src):
                p = os.path.join(os.path.dirname(in_path), rel)
                if os.path.exists(p):
                    newest = max(newest, os.path.getmtime(p))
        except Exception:
            pass
        return newest

    if os.path.exists(out_path):
        if os.path.getmtime(out_path) > _newest_input_mtime():
            print(f'[WebUI] {os.path.basename(out_path)} up-to-date, skipping.')
            return

    with open(in_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Inline-Assets (z.B. qrcode.min.js) einbetten — kein CDN nötig.
    html_inlined = inline_assets(html, os.path.dirname(in_path))
    minified     = minify_html(html_inlined)
    compressed   = gzip.compress(minified.encode('utf-8'), compresslevel=9)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Auto-generated by compress_ui.py — DO NOT EDIT\n')
        f.write(f'// Source : {os.path.basename(in_path)}\n')
        f.write(f'// Sizes  : raw={len(html)} B → inlined={len(html_inlined)} B → min={len(minified)} B → gz={len(compressed)} B\n\n')
        f.write('static const uint8_t index_html_gz[] = {\n  ')
        hex_bytes = [f'0x{b:02X}' for b in compressed]
        for i, h in enumerate(hex_bytes):
            f.write(h)
            if i < len(hex_bytes) - 1:
                f.write(', ')
                if (i + 1) % 16 == 0:
                    f.write('\n  ')
        f.write('\n};\n')
        f.write(f'static const size_t index_html_gz_len = {len(compressed)};\n')

    print(f'[WebUI] {len(html)} B (+inline {len(html_inlined)-len(html)} B) → min {len(minified)} B → gz {len(compressed)} B  ({os.path.basename(out_path)})')


if __name__ == '__main__':
    main()
