#!/usr/bin/env python3
"""
Minifies and GZIP-compresses web_ui.html → index_html_gz.h
Usage: compress_ui.py <input.html> <output.h>
"""
import sys
import os
import gzip
import re


def minify_html(content: str) -> str:
    # Remove HTML comments (keep IE conditionals)
    content = re.sub(r'<!--(?!\[if).*?-->', '', content, flags=re.DOTALL)
    # Collapse whitespace between tags
    content = re.sub(r'>\s+<', '><', content)
    # Collapse runs of whitespace
    content = re.sub(r' {2,}', ' ', content)
    lines = [line.strip() for line in content.split('\n')]
    return ''.join(line for line in lines if line)


def main():
    if len(sys.argv) != 3:
        print('Usage: compress_ui.py <input.html> <output.h>')
        sys.exit(1)

    in_path  = sys.argv[1]
    out_path = sys.argv[2]

    # Smart incremental build: skip if output is newer than input
    if os.path.exists(out_path):
        if os.path.getmtime(out_path) > os.path.getmtime(in_path):
            print(f'[WebUI] {os.path.basename(out_path)} up-to-date, skipping.')
            return

    with open(in_path, 'r', encoding='utf-8') as f:
        html = f.read()

    minified   = minify_html(html)
    compressed = gzip.compress(minified.encode('utf-8'), compresslevel=9)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Auto-generated by compress_ui.py — DO NOT EDIT\n')
        f.write(f'// Source : {os.path.basename(in_path)}\n')
        f.write(f'// Sizes  : raw={len(html)} B → min={len(minified)} B → gz={len(compressed)} B\n\n')
        f.write('static const uint8_t index_html_gz[] = {\n  ')
        hex_bytes = [f'0x{b:02X}' for b in compressed]
        for i, h in enumerate(hex_bytes):
            f.write(h)
            if i < len(hex_bytes) - 1:
                f.write(', ')
                if (i + 1) % 16 == 0:
                    f.write('\n  ')
        f.write('\n};\n')
        f.write(f'static const size_t index_html_gz_len = {len(compressed)};\n')

    print(f'[WebUI] {len(html)} B → {len(minified)} B → {len(compressed)} B  ({os.path.basename(out_path)})')


if __name__ == '__main__':
    main()
